### ISSUE TITLE
Error using version 0.2.1

### ISSUE THREAD

**Issue by aleksolutions** [toolsplus/forge-trpc#12]
I'm getting an error using version 0.2.1:

Error: Bundling failed: Module not found: Error: Can't resolve '@toolsplus/forge-trpc-adapter'
TS2307: Cannot find module '@toolsplus/forge-trpc-adapter' or its corresponding type declarations.

I had to downgrade to version 0.1.2 to fix it.

**Comment by tbinna** [comment]
Thanks for the report @aleksolutions. I will have a look at this tomorrow.
