### ISSUE TITLE
Support newer TRPC and React Query version

### ISSUE THREAD

**Issue by jackgraves** [toolsplus/forge-trpc#5]
As of the latest release, this currently supports TRPC v10.34.0 and React Query v4.29.19. 

However, both TRPC and React Query have since released new versions (TRPC v10.45.1 and React Query v5.25.0) that include significant improvements and new features that would benefit our project. Updating to these versions will help us leverage the latest improvements in performance, typesafety, and developer experience.

Motivation
The motivation for this update is twofold:

* Performance Enhancements: The latest versions of TRPC and React Query have introduced optimizations that could improve the efficiency and speed of our application.
* New Features: Both libraries have added new features that could simplify our current implementation and offer more flexibility in data fetching and state management.
* Bug Fixes and Improved Stability: Updating to the latest versions ensures we have the most stable and secure foundations, benefiting from any bug fixes and improvements made since our current versions.

**Comment by tbinna** [comment]
Hey @jackgraves, thanks for bringing this up. I would happily accept a PR if you would like to work on this. Not sure if it's just a version bump or if there are more significant changes required.

**Comment by jackgraves** [comment]
Thanks for the update @tbinna
